# WfMP containers

version: '3.5'

services:
  worker:
    build: wfmp-worker
    networks:
      - wfmpproxy-worker
    ports: 
      - 8680
  loadbalancer:
    image: dockercloud/haproxy
    ports:
      - 8680:80
    networks:
      - wfmpproxy-worker
    links:
      - worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks: 
  wfmpproxy-worker:
    external: 
      name: custom_network